"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Doctor } from "@/lib/doctors/types";

interface ServiceOption { id: string; name: string; active: boolean; }
interface Props { doctor?: Doctor; services: readonly ServiceOption[]; assignedServiceIds?: readonly string[]; canAssignServices: boolean; }

export default function DoctorForm({ doctor, services, assignedServiceIds = [], canAssignServices }: Props) {
  const router = useRouter(); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [selected, setSelected] = useState<readonly string[]>(assignedServiceIds);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(""); const form = new FormData(event.currentTarget); const payload = { fullName: String(form.get("fullName") ?? ""), email: String(form.get("email") ?? ""), phone: String(form.get("phone") ?? ""), qualification: String(form.get("qualification") ?? ""), specialisation: String(form.get("specialisation") ?? ""), registrationNumber: String(form.get("registrationNumber") ?? ""), languages: String(form.get("languages") ?? "").split(",").map((value) => value.trim()).filter(Boolean), defaultAppointmentDurationMinutes: Number(form.get("duration")), status: String(form.get("status")) };
    const response = await fetch(doctor ? `/api/admin/doctors/${doctor.id}` : "/api/admin/doctors", { method: doctor ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data: unknown = await response.json(); if (!response.ok) { setError(typeof data === "object" && data && "message" in data ? String(data.message) : "Unable to save doctor."); setSubmitting(false); return; }
    const saved = (data as { doctor: Doctor }).doctor;
    if (canAssignServices) { const assignments = selected.map((serviceId) => ({ serviceId, active: true })); const assigned = await fetch(`/api/admin/doctors/${saved.id}/services`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(assignments) }); if (!assigned.ok) { setError("Doctor saved, but services could not be assigned. Please retry."); setSubmitting(false); router.replace(`/admin/doctors/${saved.id}`); return; } }
    router.replace("/admin/doctors"); router.refresh();
  }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const photo = event.target.files?.[0]; if (!photo || !doctor) return; const form = new FormData(); form.set("photo", photo); const response = await fetch(`/api/admin/doctors/${doctor.id}/photo`, { method: "POST", body: form }); if (!response.ok) { setError("Photo upload failed. Confirm the doctor-profile-photos bucket exists."); return; } router.refresh(); }
  return <form onSubmit={submit} className="space-y-6 rounded-xl border bg-white p-5 sm:p-7"><div className="grid gap-4 md:grid-cols-2"><Field name="fullName" label="Full name" defaultValue={doctor?.fullName} required /><Field name="email" label="Email" type="email" defaultValue={doctor?.email} required /><Field name="phone" label="Phone" defaultValue={doctor?.phone ?? ""} /><Field name="qualification" label="Qualification" defaultValue={doctor?.qualification ?? ""} /><Field name="specialisation" label="Specialisation" defaultValue={doctor?.specialisation ?? ""} /><Field name="registrationNumber" label="Registration number" defaultValue={doctor?.registrationNumber ?? ""} /><Field name="languages" label="Languages" defaultValue={doctor?.languages.join(", ") ?? ""} hint="Comma-separated" /><Field name="duration" label="Default appointment duration (minutes)" type="number" defaultValue={String(doctor?.defaultAppointmentDurationMinutes ?? 30)} required /></div>
    {doctor && <label className="block text-sm font-medium text-slate-700">Profile photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="mt-1 block w-full text-sm" /></label>}
    <label className="block text-sm font-medium text-slate-700">Status<select name="status" defaultValue={doctor?.status ?? "active"} className="mt-1 block w-full rounded-lg border px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
    {canAssignServices && <fieldset><legend className="text-sm font-medium text-slate-700">Assigned clinic services</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{services.filter((service) => service.active).map((service) => <label key={service.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={selected.includes(service.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, service.id] : selected.filter((id) => id !== service.id))} />{service.name}</label>)}</div>{!services.length && <p className="mt-2 text-sm text-slate-500">No clinic services are available yet.</p>}</fieldset>}
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button disabled={submitting} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{submitting ? "Saving…" : doctor ? "Save doctor" : "Create doctor"}</button></div>
  </form>;
}
function Field({ label, hint, ...props }: { name: string; label: string; type?: string; defaultValue?: string; required?: boolean; hint?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input {...props} className="mt-1 block w-full rounded-lg border px-3 py-2 font-normal" />{hint && <span className="mt-1 block text-xs font-normal text-slate-500">{hint}</span>}</label>; }
