"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import type { DoctorPage } from "@/lib/doctors/types";

type Query = { clinicId?: string; q?: string; status?: string; sort?: string; page?: string };
export default function DoctorDirectory({ result, schedules, query, clinicId, canUpdate }: { result: DoctorPage; schedules: Readonly<Record<string, string>>; query: Query; clinicId?: string; canUpdate: boolean }) {
  const router = useRouter(); const navigate = (values: Record<string, string>) => { const next = new URLSearchParams({ ...query, ...values }); if (!next.get("q")) next.delete("q"); if (!next.get("status")) next.delete("status"); next.delete("page"); router.push(`/admin/doctors?${next}`); }; const pages = Math.max(Math.ceil(result.total / result.pageSize), 1);
  return <section className="space-y-4"><form className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-3" onSubmit={(event) => { event.preventDefault(); navigate({ q: new FormData(event.currentTarget).get("q")?.toString() ?? "" }); }}><input name="q" defaultValue={query.q} placeholder="Search name, email, specialty" className="rounded-lg border px-3 py-2" /><select defaultValue={query.status ?? ""} onChange={(event) => navigate({ status: event.target.value })} className="rounded-lg border px-3 py-2"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select defaultValue={query.sort ?? "name"} onChange={(event) => navigate({ sort: event.target.value })} className="rounded-lg border px-3 py-2"><option value="name">Name</option><option value="created">Recently added</option></select></form>{!result.doctors.length ? <div className="rounded-xl border bg-white p-12 text-center text-sm text-slate-500">No doctors match these filters.</div> : <div className="overflow-hidden rounded-xl border bg-white"><div className="grid gap-3 p-4 md:hidden">{result.doctors.map((doctor) => <Card key={doctor.id} doctor={doctor} schedule={schedules[doctor.id]} edit={editUrl(doctor.id, clinicId)} canUpdate={canUpdate} />)}</div><table className="hidden min-w-full text-sm md:table"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="p-4">Doctor</th><th className="p-4">Specialisation</th><th className="p-4">Schedule</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{result.doctors.map((doctor) => <tr key={doctor.id} className="border-t"><td className="p-4"><p className="font-medium">{doctor.fullName}</p><p className="text-slate-500">{doctor.email}</p></td><td className="p-4">{doctor.specialisation ?? "—"}</td><td className="p-4">{schedules[doctor.id] ?? "No schedule configured"}</td><td className="p-4"><Status value={doctor.status} /></td><td className="p-4">{canUpdate && <Link href={editUrl(doctor.id, clinicId)} className="text-blue-700 hover:underline">Edit</Link>}</td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between text-sm"><span className="text-slate-500">{result.total} doctors</span><div className="flex gap-2"><button disabled={result.page <= 1} onClick={() => router.push(`/admin/doctors?${new URLSearchParams({ ...query, page: String(result.page - 1) })}`)} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5">{result.page} / {pages}</span><button disabled={result.page >= pages} onClick={() => router.push(`/admin/doctors?${new URLSearchParams({ ...query, page: String(result.page + 1) })}`)} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div></section>;
}
function editUrl(id: string, clinicId?: string) { return `/admin/doctors/${id}${clinicId ? `?clinicId=${clinicId}` : ""}`; }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${value === "active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-700"}`}>{value}</span>; }
function Card({ doctor, schedule, edit, canUpdate }: { doctor: DoctorPage["doctors"][number]; schedule?: string; edit: string; canUpdate: boolean }) { return <article className="rounded-lg border p-4"><div className="flex items-start justify-between"><div><p className="font-semibold">{doctor.fullName}</p><p className="text-sm text-slate-500">{doctor.specialisation ?? doctor.email}</p></div><Status value={doctor.status} /></div><p className="mt-3 text-sm">{schedule ?? "No schedule configured"}</p>{canUpdate && <Link href={edit} className="mt-3 inline-block text-sm font-medium text-blue-700">Edit doctor</Link>}</article>; }
