import { NextRequest, NextResponse } from "next/server";
import { requireAnyPermission } from "@/lib/infrastructure/identity/AuthorizationContext";
import { Permissions } from "@/lib/platform/domain/identity";
import { resolveSchedulingDoctor } from "@/lib/scheduling/authorization";
import { createSchedulingService } from "@/lib/scheduling/service";
type Context = { params: Promise<{ id: string; scheduleId: string }> };
async function resolve(request: NextRequest, context: Context) { const auth = requireAnyPermission(request, [Permissions.SchedulesUpdate, Permissions.CalendarUpdateOwn]); if (auth instanceof Response) return auth; try { const params = await context.params; return { scope: await resolveSchedulingDoctor(auth, params.id, request.nextUrl.searchParams.get("clinicId")), id: params.scheduleId }; } catch { return NextResponse.json({ message: "Doctor schedule access is not permitted." }, { status: 403 }); } }
function input(body: Record<string, unknown>) { return { weekday: Number(body.weekday), startTime: String(body.startTime ?? ""), endTime: String(body.endTime ?? ""), breakStartTime: typeof body.breakStartTime === "string" ? body.breakStartTime : undefined, breakEndTime: typeof body.breakEndTime === "string" ? body.breakEndTime : undefined, effectiveFrom: typeof body.effectiveFrom === "string" ? body.effectiveFrom : undefined, effectiveTo: typeof body.effectiveTo === "string" ? body.effectiveTo : undefined, timezone: String(body.timezone ?? "UTC") }; }
export async function PATCH(request: NextRequest, context: Context) { const resolved = await resolve(request, context); if (resolved instanceof Response) return resolved; try { return NextResponse.json({ schedule: await createSchedulingService().updateSchedule(resolved.scope.clinicId, resolved.scope.doctorId, resolved.id, input(await request.json() as Record<string, unknown>)) }); } catch { return NextResponse.json({ message: "Unable to update schedule." }, { status: 400 }); } }
export async function DELETE(request: NextRequest, context: Context) { const resolved = await resolve(request, context); if (resolved instanceof Response) return resolved; await createSchedulingService().deactivateSchedule(resolved.scope.clinicId, resolved.id); return new NextResponse(null, { status: 204 }); }
