"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/browser";
import { validateNewPassword } from "@/lib/auth/password-recovery";

export default function SetPasswordPage() {
  const router = useRouter(); const [ready, setReady] = useState(false); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const client = createClient(); let active = true; void client.auth.getSession().then(({ data }) => { if (active) setReady(Boolean(data.session)); }); return () => { active = false; }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const validation = validateNewPassword(password); if (validation) return setError(validation); if (password !== confirmation) return setError("Passwords do not match."); setSaving(true); setError(""); const client = createClient(); const { error: updateError } = await client.auth.updateUser({ password }); if (updateError) { setError("This activation link is invalid or has expired."); setSaving(false); return; } const { data } = await client.auth.getSession(); const token = data.session?.access_token; if (!token) { setError("This activation link is invalid or has expired."); setSaving(false); return; } const complete = await fetch("/api/auth/complete-owner-activation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ accessToken: token }) }); if (!complete.ok) { setError("Your password was set, but account activation requires support assistance."); setSaving(false); return; } await client.auth.signOut(); router.replace("/login?activation=success"); }
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 px-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-xl"><h1 className="text-center text-3xl font-bold">Activate your account</h1><p className="mt-2 text-center text-sm text-slate-500">Choose a strong password to access your clinic dashboard.</p><label className="mt-6 grid gap-2 text-sm font-medium">New password<input type="password" autoComplete="new-password" disabled={!ready || saving} value={password} onChange={(event) => setPassword(event.target.value)} className="min-h-11 rounded-lg border px-3" required /></label><label className="mt-4 grid gap-2 text-sm font-medium">Confirm password<input type="password" autoComplete="new-password" disabled={!ready || saving} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="min-h-11 rounded-lg border px-3" required /></label>{!ready && <p role="alert" className="mt-4 text-sm text-red-600">This activation link is invalid or has expired.</p>}{error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={!ready || saving} className="mt-6 min-h-11 w-full rounded-lg bg-blue-600 font-semibold text-white disabled:opacity-60">{saving ? "Activating…" : "Set password"}</button></form></main>;
}
