import "server-only";

/** Pure, tenant-scoped availability calculation. Repository loading belongs at the caller boundary. */
export type AvailabilityReason = "AVAILABLE" | "CLINIC_CLOSED" | "MINIMUM_NOTICE" | "OUTSIDE_BOOKING_HORIZON" | "SERVICE_INACTIVE" | "DOCTOR_NOT_ELIGIBLE" | "DOCTOR_NOT_SCHEDULED" | "DOCTOR_ON_LEAVE" | "DOCTOR_BLOCKED" | "DOCTOR_CONFLICT" | "NO_VALID_ROOM" | "ROOM_CONFLICT" | "CLINIC_NOT_READY";
export type AvailabilitySlot = { date: string; startTime: string; endTime: string; doctorId: string; serviceId: string; roomId: string; durationMinutes: number; timezone: string; reason: "AVAILABLE" };
export type AvailabilityInput = { clinicReady: boolean; timezone: string; date: string; startTime: string; serviceId: string; doctorId?: string; durationMinutes: number; intervalMinutes: number; minimumNoticeMinutes: number; maximumHorizonDays: number; officeHours: Record<string, { enabled: boolean; open: string; close: string }>; doctors: { id: string; active: boolean }[]; assignments: { doctorId: string; serviceId: string; active: boolean; durationMinutes?: number | null }[]; schedules: { doctorId: string; weekday: number; start: string; end: string; active: boolean; effectiveFrom?: string | null; effectiveTo?: string | null }[]; leave: { doctorId: string; startsOn: string; endsOn: string; active: boolean }[]; blocks: { doctorId?: string | null; roomId?: string | null; startsAt: string; endsAt: string; active: boolean }[]; rooms: { id: string; active: boolean }[]; roomAssignments: { doctorId: string; roomId: string; active: boolean; effectiveFrom?: string | null; effectiveTo?: string | null }[]; appointments: { id: string; doctorId?: string | null; roomId?: string | null; date: string; time: string; durationMinutes: number | null; status: string }[]; excludeAppointmentId?: string; now?: Date };
export type AvailabilityResult = { available: boolean; reason: AvailabilityReason; slots: AvailabilitySlot[] };

export function checkSlotAvailability(input: AvailabilityInput): AvailabilityResult {
  if (!input.clinicReady) return unavailable("CLINIC_NOT_READY");
  const start = minutes(input.startTime); if (start === null || !validDate(input.date) || input.durationMinutes <= 0) return unavailable("CLINIC_CLOSED");
  const now = input.now ?? new Date(); const localToday = localDate(now, input.timezone); const requestedAt = zonedEpoch(input.date, input.startTime, input.timezone); if (!localToday || requestedAt === null) return unavailable("CLINIC_CLOSED"); const earliest = now.getTime() + input.minimumNoticeMinutes * 60000; if (input.date < localToday || requestedAt < earliest) return unavailable("MINIMUM_NOTICE"); if (daysBetween(localToday, input.date) > input.maximumHorizonDays) return unavailable("OUTSIDE_BOOKING_HORIZON");
  const day = weekday(input.date); const office = input.officeHours[String(day)] ?? input.officeHours[["sunday","monday","tuesday","wednesday","thursday","friday","saturday"][day]]; if (!office?.enabled || !inside(start, input.durationMinutes, office.open, office.close)) return unavailable("CLINIC_CLOSED");
  const doctors = input.doctors.filter((doctor) => doctor.active && (!input.doctorId || doctor.id === input.doctorId) && input.assignments.some((assignment) => assignment.active && assignment.doctorId === doctor.id && assignment.serviceId === input.serviceId)); if (!doctors.length) return unavailable(input.doctorId ? "DOCTOR_NOT_ELIGIBLE" : "SERVICE_INACTIVE");
  const reasons: AvailabilityReason[] = []; for (const doctor of doctors) { const result = doctorSlot(input, doctor.id, start); if (result.slot) return { available: true, reason: "AVAILABLE", slots: [result.slot] }; reasons.push(result.reason); }
  return unavailable(reasons.find((reason) => reason !== "DOCTOR_NOT_SCHEDULED") ?? "DOCTOR_NOT_SCHEDULED");
}

export function getAvailableSlots(input: Omit<AvailabilityInput, "startTime">, fromTime = "00:00", limit = 12): AvailabilityResult {
  const slots: AvailabilitySlot[] = []; for (let start = minutes(fromTime) ?? 0; start < 1440 && slots.length < limit; start += input.intervalMinutes) { const result = checkSlotAvailability({ ...input, startTime: clock(start) }); if (result.available) slots.push(...result.slots); }
  return slots.length ? { available: true, reason: "AVAILABLE", slots } : unavailable("DOCTOR_NOT_SCHEDULED");
}

function doctorSlot(input: AvailabilityInput, doctorId: string, start: number): { slot?: AvailabilitySlot; reason: AvailabilityReason } { const schedule = input.schedules.some((row) => row.active && row.doctorId === doctorId && row.weekday === weekday(input.date) && current(row.effectiveFrom, row.effectiveTo, input.date) && inside(start, input.durationMinutes, row.start, row.end)); if (!schedule) return { reason: "DOCTOR_NOT_SCHEDULED" }; if (input.leave.some((row) => row.active && row.doctorId === doctorId && row.startsOn <= input.date && row.endsOn >= input.date)) return { reason: "DOCTOR_ON_LEAVE" }; const end = start + input.durationMinutes; if (input.blocks.some((row) => row.active && row.doctorId === doctorId && overlap(start, end, stampMinutes(row.startsAt), stampMinutes(row.endsAt)))) return { reason: "DOCTOR_BLOCKED" }; if (input.appointments.some((row) => row.id !== input.excludeAppointmentId && row.doctorId === doctorId && consumes(row.status) && row.date === input.date && overlap(start, end, minutes(row.time), (minutes(row.time) ?? 0) + (row.durationMinutes ?? 0)))) return { reason: "DOCTOR_CONFLICT" }; const rooms = input.roomAssignments.filter((row) => row.active && row.doctorId === doctorId && current(row.effectiveFrom, row.effectiveTo, input.date)).map((row) => row.roomId).filter((id) => input.rooms.some((room) => room.id === id && room.active)); if (!rooms.length) return { reason: "NO_VALID_ROOM" }; let roomConflict = false; for (const roomId of rooms.sort()) { const blocked = input.blocks.some((row) => row.active && row.roomId === roomId && overlap(start, end, stampMinutes(row.startsAt), stampMinutes(row.endsAt))); const conflict = input.appointments.some((row) => row.id !== input.excludeAppointmentId && row.roomId === roomId && consumes(row.status) && row.date === input.date && overlap(start, end, minutes(row.time), (minutes(row.time) ?? 0) + (row.durationMinutes ?? 0))); if (!blocked && !conflict) return { slot: { date: input.date, startTime: clock(start), endTime: clock(end), doctorId, serviceId: input.serviceId, roomId, durationMinutes: input.durationMinutes, timezone: input.timezone, reason: "AVAILABLE" }, reason: "AVAILABLE" }; roomConflict ||= blocked || conflict; } return { reason: roomConflict ? "ROOM_CONFLICT" : "NO_VALID_ROOM" }; }
function unavailable(reason: AvailabilityReason): AvailabilityResult { return { available: false, reason, slots: [] }; } function minutes(value: string | null | undefined): number | null { const match = /^(\d{1,2}):(\d{2})/.exec(value ?? ""); return match && Number(match[1]) < 24 && Number(match[2]) < 60 ? Number(match[1]) * 60 + Number(match[2]) : null; } function stampMinutes(value: string): number | null { return minutes(value.slice(11, 16)); } function clock(value: number): string { return `${String(Math.floor(value / 60)).padStart(2,"0")}:${String(value % 60).padStart(2,"0")}`; } function inside(start: number, duration: number, open: string, close: string): boolean { const begin = minutes(open), end = minutes(close); return begin !== null && end !== null && start >= begin && start + duration <= end; } function overlap(start: number, end: number, existingStart: number | null, existingEnd: number | null): boolean { return existingStart !== null && existingEnd !== null && start < existingEnd && end > existingStart; } function current(from: string | null | undefined, to: string | null | undefined, date: string): boolean { return (!from || from <= date) && (!to || to >= date); } function consumes(status: string): boolean { return !["Cancelled", "Completed"].includes(status); } function weekday(date: string): number { return new Date(`${date}T00:00:00Z`).getUTCDay(); } function validDate(value: string): boolean { return /^\d{4}-\d{2}-\d{2}$/.test(value); } function daysBetween(from: string, to: string): number { return Math.floor((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86400000); } function localDate(now: Date, timezone: string): string | null { try { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year:"numeric",month:"2-digit",day:"2-digit" }).formatToParts(now); const value = Object.fromEntries(parts.map((part) => [part.type,part.value])); return `${value.year}-${value.month}-${value.day}`; } catch { return null; } }
function zonedEpoch(date: string, time: string, timezone: string): number | null { try { const expected = `${date}, ${time}`; const base = Date.parse(`${date}T${time}:00Z`); const formatter = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }); const local = (epoch: number) => { const parts = Object.fromEntries(formatter.formatToParts(new Date(epoch)).filter((part) => part.type !== "literal").map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}, ${parts.hour}:${parts.minute}`; }; const first = local(base); const [wantedDate, wantedTime] = expected.split(", "); const [actualDate, actualTime] = first.split(", "); const delta = (Date.parse(`${wantedDate}T${wantedTime}:00Z`) - Date.parse(`${actualDate}T${actualTime}:00Z`)); const result = base + delta; return local(result) === expected ? result : null; } catch { return null; } }
