import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
test("temporary Supabase Auth adapter fails closed and derives administrator clinic permissions", () => {
  const adapter = read("lib/infrastructure/identity/SupabaseAuthCompatibilityAdapter.ts");
  const rolePolicy = read("lib/auth/profile-role-policy.ts");
  const sql = read("lib/supabase/migrations/0013_india_supabase_auth_profile_bootstrap.sql");
  assert.match(adapter, /auth\.getUser/);
  assert.match(adapter, /profiles/);
  assert.match(adapter, /if \(error\) throw error/);
  assert.match(adapter, /if \(!profile\?\.clinic_id \|\| !profile\.role\) return \{ identity: null/);
  assert.match(adapter, /resolveProfileRolePolicy/);
  assert.match(rolePolicy, /super_admin: "super-admin"/);
  assert.match(rolePolicy, /permissionsForRole/);
  assert.match(sql, /Bootstrap auth user is missing/);
  assert.match(sql, /Bootstrap clinic is missing/);
  assert.match(sql, /different clinic or role/);
  assert.match(sql, /'super_admin'/);
  assert.doesNotMatch(sql, /user_credentials|password_hash/);
});
