/**
 * ============================================================
 * PatientPilot AI
 * Session ID Value Object
 * ============================================================
 *
 * Represents a validated session identifier.
 *
 * Domain Rules:
 * - Immutable
 * - Non-empty
 * - UUID compatible
 * - Comparable
 * - Framework independent
 *
 * NOTE:
 * Session IDs are generated by the Infrastructure Layer.
 */

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export class SessionId {
  /**
   * Session identifier.
   */
  public readonly value: string;

  private constructor(
    value: string,
  ) {
    this.value = value;

    Object.freeze(this);
  }

  /**
   * Creates a validated SessionId.
   */
  static create(
    value: string,
  ): SessionId {
    const normalized =
      SessionId.normalize(value);

    if (!SessionId.isValid(normalized)) {
      throw new Error(
        `Invalid session identifier: "${value}".`,
      );
    }

    return new SessionId(normalized);
  }

  /**
   * Normalizes the identifier.
   */
  static normalize(
    value: string,
  ): string {
    return value.trim().toLowerCase();
  }

  /**
   * Returns true if the supplied value is a valid UUID.
   */
  static isValid(
    value: string,
  ): boolean {
    if (!value) {
      return false;
    }

    return UUID_PATTERN.test(value);
  }

  /**
   * Compares two SessionIds.
   */
  equals(
    other: SessionId,
  ): boolean {
    return this.value === other.value;
  }

  /**
   * Returns the identifier.
   */
  toString(): string {
    return this.value;
  }

  /**
   * JSON serialization.
   */
  toJSON(): string {
    return this.value;
  }
}