import Link from "next/link";
import { Bot, Mail } from "lucide-react";

const columns = [
  { title: "Home", links: [{ label: "Home", href: "/" }, { label: "About", href: "/about" }, { label: "Contact", href: "/contact" }] },
  { title: "Solutions", links: [{ label: "Solutions", href: "/solutions" }, { label: "AI Receptionist", href: "/solutions" }, { label: "Smart Scheduling", href: "/solutions" }] },
  { title: "Pricing", links: [{ label: "Pricing", href: "/pricing" }, { label: "Compare Plans", href: "/pricing" }, { label: "ROI Calculator", href: "/pricing" }] },
  { title: "Book Demo", links: [{ label: "Book Demo", href: "/book-demo" }, { label: "Contact", href: "/contact" }, { label: "Free Demo", href: "/book-demo" }] },
] as const;

export default function Footer() {
  return <footer className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 pb-10 pt-12 sm:px-7 md:grid-cols-[minmax(0,1.5fr)_repeat(4,minmax(0,1fr))] md:gap-8 md:py-16"><div className="max-w-sm"><Link href="/" aria-label="PatientPilot AI home" className="inline-flex items-center gap-4 rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-400 shadow-lg shadow-blue-950/40 sm:h-16 sm:w-16"><Bot aria-hidden="true" className="h-8 w-8 text-white" /></span><span className="min-w-0"><span className="block whitespace-nowrap text-2xl font-bold tracking-tight">PatientPilot <span className="text-cyan-400">AI</span></span><span className="mt-1 block text-[10px] font-semibold tracking-[0.14em] text-slate-200">AI RECEPTIONIST FOR DENTAL PRACTICES</span></span></Link><p className="mt-6 text-sm leading-6 text-slate-300 sm:text-base">AI Receptionist built for modern dental practices.<br />Never miss another patient call.</p></div><nav aria-label="Footer navigation" className="grid grid-cols-2 gap-x-6 gap-y-8 sm:grid-cols-4 md:col-span-4 md:grid-cols-4">{columns.map((column) => <section key={column.title}><h2 className="text-sm font-semibold text-white">{column.title}</h2><ul className="mt-3 space-y-1">{column.links.map((link) => <li key={`${column.title}-${link.label}`}><Link href={link.href} className="flex min-h-11 items-center rounded-md text-sm text-slate-300 transition hover:text-cyan-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950">{link.label}</Link></li>)}</ul></section>)}</nav></div><div className="border-t border-slate-700/70"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-7 text-sm text-slate-400 sm:px-7"><p>© 2026 PatientPilot AI. All rights reserved.</p><a href="mailto:support@patientpilotai.com" aria-label="Email PatientPilot AI support" className="inline-flex min-h-11 items-center gap-2 rounded-md text-slate-300 transition hover:text-cyan-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950"><Mail aria-hidden="true" className="h-4 w-4" /><span>support@patientpilotai.com</span></a></div></div></footer>;
}
