"use client";

import { Mail, UserRound } from "lucide-react";
import type { ClinicOwnerAccount } from "@/lib/clinic/owner-account";

export default function ClinicOwnerAccountForm({ value, onChange, disabled = false }: { value: ClinicOwnerAccount; onChange: (value: ClinicOwnerAccount) => void; disabled?: boolean }) {
  const update = <K extends keyof ClinicOwnerAccount>(key: K, next: ClinicOwnerAccount[K]) => onChange({ ...value, [key]: next });
  return <section className="rounded-xl border bg-background p-4 sm:p-6 lg:p-8"><div className="mb-6 flex items-start gap-3"><div className="rounded-lg bg-blue-100 p-3"><UserRound className="h-6 w-6 text-blue-600" /></div><div><h2 className="text-xl font-semibold">Owner account</h2><p className="text-sm text-muted-foreground">This is the owner&apos;s secure sign-in identity. It remains separate from the clinic contact email.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Owner full name<input required value={value.fullName} disabled={disabled} onChange={(event) => update("fullName", event.target.value)} className="min-h-11 rounded-lg border bg-background px-3" /></label><label className="grid gap-2 text-sm font-medium">Owner email<input required type="email" value={value.email} disabled={disabled} onChange={(event) => update("email", event.target.value)} className="min-h-11 rounded-lg border bg-background px-3" /></label><label className="grid gap-2 text-sm font-medium">Role<select value={value.role} disabled={disabled} onChange={(event) => update("role", event.target.value as ClinicOwnerAccount["role"])} className="min-h-11 rounded-lg border bg-background px-3"><option value="owner">Owner</option><option value="manager">Manager</option></select></label><label className="flex min-h-11 items-center gap-2 self-end text-sm font-medium"><input type="checkbox" checked={value.sendInvitation} disabled={disabled} onChange={(event) => update("sendInvitation", event.target.checked)} />Send activation email now</label></div><p className="mt-4 flex items-center gap-2 text-sm text-muted-foreground"><Mail className="h-4 w-4" />Activation links are one-time; no temporary password is sent.</p></section>;
}
