import { NextRequest, NextResponse } from "next/server";
import { requirePermission } from "@/lib/infrastructure/identity/AuthorizationContext";
import { Permissions } from "@/lib/platform/domain/identity";
import { resolveDoctorClinic } from "@/lib/doctors/clinic-context";
import { createSchedulingService } from "@/lib/scheduling/service";
type Context = { params: Promise<{ id: string; assignmentId: string }> };
async function resolve(request: NextRequest, context: Context) { const auth = requirePermission(request, Permissions.SchedulesUpdate); if (auth instanceof Response) return auth; const params = await context.params; return { clinicId: await resolveDoctorClinic(auth, request.nextUrl.searchParams.get("clinicId")), id: params.assignmentId }; }
export async function PATCH(request: NextRequest, context: Context) { const resolved = await resolve(request, context); if (resolved instanceof Response) return resolved; try { const body = await request.json() as Record<string, unknown>; return NextResponse.json({ assignment: await createSchedulingService().updateRoomAssignment(resolved.clinicId, resolved.id, { roomId: String(body.roomId ?? ""), effectiveFrom: typeof body.effectiveFrom === "string" ? body.effectiveFrom : undefined, effectiveTo: typeof body.effectiveTo === "string" ? body.effectiveTo : undefined }) }); } catch { return NextResponse.json({ message: "Unable to update room assignment." }, { status: 400 }); } }
export async function DELETE(request: NextRequest, context: Context) { const resolved = await resolve(request, context); if (resolved instanceof Response) return resolved; const body = await request.json().catch(() => ({})) as Record<string, unknown>; const effectiveTo = typeof body.effectiveTo === "string" ? body.effectiveTo : new Date().toISOString().slice(0, 10); try { await createSchedulingService().endRoomAssignment(resolved.clinicId, resolved.id, effectiveTo); return new NextResponse(null, { status: 204 }); } catch { return NextResponse.json({ message: "Unable to end room assignment." }, { status: 400 }); } }
