import { NextRequest, NextResponse } from "next/server";
import { requireAnyPermission } from "@/lib/infrastructure/identity/AuthorizationContext";
import { Permissions } from "@/lib/platform/domain/identity";
import { resolveSchedulingDoctor } from "@/lib/scheduling/authorization";
import { createSchedulingService } from "@/lib/scheduling/service";
type Context = { params: Promise<{ id: string }> };
async function scope(request: NextRequest, context: Context, permissions: readonly (typeof Permissions)[keyof typeof Permissions][]) { const auth = requireAnyPermission(request, permissions); if (auth instanceof Response) return auth; try { return resolveSchedulingDoctor(auth, (await context.params).id, request.nextUrl.searchParams.get("clinicId")); } catch { return NextResponse.json({ message: "Blocked-time access is not permitted." }, { status: 403 }); } }
export async function GET(request: NextRequest, context: Context) { const resolved = await scope(request, context, [Permissions.CalendarRead, Permissions.CalendarReadOwn]); if (resolved instanceof Response) return resolved; return NextResponse.json({ blockedTime: await createSchedulingService().blockedTime(resolved.clinicId, resolved.doctorId) }); }
export async function POST(request: NextRequest, context: Context) { const resolved = await scope(request, context, [Permissions.CalendarUpdate, Permissions.CalendarUpdateOwn]); if (resolved instanceof Response) return resolved; try { const body = await request.json() as Record<string, unknown>; return NextResponse.json({ blockedTime: await createSchedulingService().addBlockedTime(resolved.clinicId, { doctorId: resolved.doctorId, roomId: typeof body.roomId === "string" ? body.roomId : undefined, startsAt: String(body.startsAt ?? ""), endsAt: String(body.endsAt ?? ""), source: typeof body.source === "string" ? body.source : undefined }) }, { status: 201 }); } catch { return NextResponse.json({ message: "Unable to save blocked time." }, { status: 400 }); } }
