import { NextRequest, NextResponse } from "next/server";
import { requireAnyPermission } from "@/lib/infrastructure/identity/AuthorizationContext";
import { Permissions } from "@/lib/platform/domain/identity";
import { createSchedulingService } from "@/lib/scheduling/service";
import { resolveSchedulingDoctor } from "@/lib/scheduling/authorization";

const scope = async (request: NextRequest, params: Promise<{ id: string }>, permissions: readonly (typeof Permissions)[keyof typeof Permissions][]) => { const auth = requireAnyPermission(request, permissions); if (auth instanceof Response) return auth; try { return await resolveSchedulingDoctor(auth, (await params).id, request.nextUrl.searchParams.get("clinicId")); } catch { return NextResponse.json({ message: "Doctor schedule access is not permitted." }, { status: 403 }); } };
const input = (body: Record<string, unknown>) => ({ weekday: Number(body.weekday), startTime: String(body.startTime ?? ""), endTime: String(body.endTime ?? ""), breakStartTime: typeof body.breakStartTime === "string" ? body.breakStartTime : undefined, breakEndTime: typeof body.breakEndTime === "string" ? body.breakEndTime : undefined, effectiveFrom: typeof body.effectiveFrom === "string" ? body.effectiveFrom : undefined, effectiveTo: typeof body.effectiveTo === "string" ? body.effectiveTo : undefined, timezone: String(body.timezone ?? "UTC") });
export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const resolved = await scope(request, params, [Permissions.SchedulesRead, Permissions.CalendarReadOwn]); if (resolved instanceof Response) return resolved; return NextResponse.json({ schedules: await createSchedulingService().schedules(resolved.clinicId, resolved.doctorId) }); }
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const resolved = await scope(request, params, [Permissions.SchedulesUpdate, Permissions.CalendarUpdateOwn]); if (resolved instanceof Response) return resolved; try { return NextResponse.json({ schedule: await createSchedulingService().addSchedule(resolved.clinicId, resolved.doctorId, input(await request.json() as Record<string, unknown>)) }, { status: 201 }); } catch { return NextResponse.json({ message: "Unable to save schedule." }, { status: 400 }); } }
