"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Service = { id: string; name: string; defaultDurationMinutes: number | null };
type Doctor = { id: string; fullName: string; serviceIds: readonly string[]; durationByService: Readonly<Record<string, number | null>> };
type Room = { id: string; name: string };
type Existing = { id: string; patientName: string; phone: string | null; email: string | null; service: string; serviceId: string | null; doctorId: string | null; roomId: string | null; appointmentDate: string; appointmentTime: string; durationMinutes: number | null; status: string; source: string; notes: string | null };

export default function AppointmentForm({ services, doctors, rooms, appointment }: { services: readonly Service[]; doctors: readonly Doctor[]; rooms: readonly Room[]; appointment?: Existing }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [serviceId, setServiceId] = useState(appointment?.serviceId ?? ""); const [doctorId, setDoctorId] = useState(appointment?.doctorId ?? "");
  const eligibleDoctors = useMemo(() => serviceId ? doctors.filter((doctor) => doctor.serviceIds.includes(serviceId)) : doctors, [doctors, serviceId]); const selectedService = services.find((service) => service.id === serviceId); const selectedDoctor = doctors.find((doctor) => doctor.id === doctorId); const resolvedDuration = selectedDoctor?.durationByService[serviceId] ?? selectedService?.defaultDurationMinutes ?? appointment?.durationMinutes ?? 30;
  async function submit(formData: FormData) { setSaving(true); setError(null); const data = Object.fromEntries(formData); const payload = { patientName: data.patientName, phone: data.phone, email: data.email, service: services.find((service) => service.id === serviceId)?.name ?? data.service, serviceId: serviceId || undefined, doctorId: doctorId || undefined, roomId: data.roomId || undefined, appointmentDate: data.appointmentDate, appointmentTime: data.appointmentTime, durationMinutes: Number(data.durationMinutes), status: data.status, source: data.source, notes: data.notes }; const response = await fetch(appointment ? `/api/appointments/${appointment.id}` : "/api/appointments", { method: appointment ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { const result = await response.json().catch(() => ({})); setError(result.message ?? "Unable to save appointment."); setSaving(false); return; } router.push("/admin/appointments"); router.refresh(); }
  return <form action={async (form) => submit(form)} className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2"><Field label="Patient name" name="patientName" required defaultValue={appointment?.patientName} /><Field label="Phone" name="phone" required defaultValue={appointment?.phone ?? ""} /><Field label="Email" name="email" type="email" defaultValue={appointment?.email ?? ""} /><label className="grid gap-1 text-sm font-medium">Service<select required name="serviceId" value={serviceId} onChange={(event) => { setServiceId(event.target.value); setDoctorId(""); }} className="rounded-lg border px-3 py-2"><option value="">Select service</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Doctor<select name="doctorId" value={doctorId} onChange={(event) => setDoctorId(event.target.value)} className="rounded-lg border px-3 py-2" disabled={!serviceId}><option value="">Select doctor</option>{eligibleDoctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.fullName}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Room / chair<select name="roomId" defaultValue={appointment?.roomId ?? ""} className="rounded-lg border px-3 py-2"><option value="">No room</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><Field label="Date" name="appointmentDate" type="date" required defaultValue={appointment?.appointmentDate} /><Field label="Time" name="appointmentTime" type="time" required defaultValue={appointment?.appointmentTime} /><label className="grid gap-1 text-sm font-medium">Duration (minutes)<input name="durationMinutes" type="number" min="1" value={resolvedDuration} readOnly className="rounded-lg border bg-slate-50 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">Status<select name="status" defaultValue={appointment?.status ?? "Confirmed"} className="rounded-lg border px-3 py-2"><option>Confirmed</option><option>Rescheduled</option><option>Cancelled</option></select></label><Field label="Source" name="source" defaultValue={appointment?.source ?? "Admin"} /><label className="grid gap-1 text-sm font-medium sm:col-span-2">Notes<textarea name="notes" defaultValue={appointment?.notes ?? ""} rows={3} className="rounded-lg border px-3 py-2" /></label>{error && <p role="alert" className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="flex gap-3 sm:col-span-2"><button disabled={saving} className="min-h-11 rounded-lg bg-blue-600 px-5 font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : appointment ? "Save appointment" : "Create appointment"}</button></div></form>;
}
function Field({ label, name, type = "text", required, defaultValue }: { label: string; name: string; type?: string; required?: boolean; defaultValue?: string | null }) { return <label className="grid gap-1 text-sm font-medium">{label}<input name={name} type={type} required={required} defaultValue={defaultValue ?? ""} className="rounded-lg border px-3 py-2" /></label>; }
