"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export default function DoctorAdministrationControls({ doctorId, clinicId, fullName, status, canDeactivate, canDelete }: { doctorId: string; clinicId?: string; fullName: string; status: "active" | "inactive"; canDeactivate: boolean; canDelete: boolean }) {
  const router = useRouter(); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function updateStatus() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/doctors/${doctorId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: status === "active" ? "inactive" : "active", ...(clinicId ? { clinicId } : {}) }) }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(typeof result.message === "string" ? result.message : "Unable to update doctor status."); else router.refresh(); } finally { setBusy(false); } }
  async function remove() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/doctors/${doctorId}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation, ...(clinicId ? { clinicId } : {}) }) }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(typeof result.message === "string" ? result.message : "Doctor was not deleted."); else router.push("/admin/doctors"); } finally { setBusy(false); } }
  return <section className="space-y-4"><div className="rounded-2xl border p-5"><h2 className="font-semibold">Doctor status</h2><p className="mt-1 text-sm text-muted-foreground">This doctor is currently <span className="font-medium">{status}</span>. Deactivation preserves appointments and clinical history.</p>{canDeactivate && <button type="button" disabled={busy} onClick={() => void updateStatus()} className="mt-4 min-h-11 rounded-lg border px-4 text-sm font-medium disabled:opacity-50">{status === "active" ? "Deactivate doctor" : "Reactivate doctor"}</button>}</div>{canDelete && <div className="rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="font-semibold text-red-950">Danger zone</h2><p className="mt-1 text-sm text-red-800">Permanent deletion is limited to dependency-free doctors. Deactivate instead when history exists.</p><label className="mt-4 block text-sm font-medium text-red-950">Type <span className="font-semibold">{fullName}</span> to delete</label><div className="mt-2 flex flex-wrap gap-3"><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="min-h-11 min-w-64 rounded-lg border border-red-200 bg-white px-3" /><button type="button" disabled={busy || confirmation !== fullName} onClick={() => void remove()} className="min-h-11 rounded-lg bg-red-700 px-4 text-sm font-medium text-white disabled:opacity-50">Delete doctor</button></div></div>}{message && <p role="alert" className="text-sm text-red-700">{message}</p>}</section>;
}
