"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Entry = { id: string; active: boolean; weekday?: number; start_time?: string; end_time?: string; break_start_time?: string | null; break_end_time?: string | null; timezone?: string; effective_from?: string | null; effective_to?: string | null; starts_on?: string; ends_on?: string; reason?: string | null; starts_at?: string; ends_at?: string; source?: string | null; room_id?: string };
type Room = { id: string; name: string };
type EditKind = "schedule" | "leave" | "block" | "assignment";

export default function DoctorSchedulingPanel({ doctorId, clinicId, schedules, leave, blocked, assignments, rooms, permissions }: { doctorId: string; clinicId?: string; schedules: Entry[]; leave: Entry[]; blocked: Entry[]; assignments: Entry[]; rooms: Room[]; permissions: { schedule: boolean; leave: boolean; block: boolean; assignment: boolean } }) {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [saving, setSaving] = useState<string | null>(null);
  const [editing, setEditing] = useState<{ kind: EditKind; entry: Entry } | null>(null);
  const suffix = clinicId ? `?clinicId=${encodeURIComponent(clinicId)}` : "";
  const endpoint = (path: string) => `${path}${suffix}`;

  async function send(path: string, method: string, body?: Record<string, unknown>, message = "Saved changes.") {
    setSaving(`${method}:${path}`); setError(null); setSuccess(null);
    try {
      const response = await fetch(endpoint(path), { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
      if (!response.ok) { const data = await response.json().catch(() => ({})); setError(data.message ?? "Unable to save changes."); return false; }
      setSuccess(message); router.refresh(); return true;
    } catch { setError("Unable to save changes. Check your connection and try again."); return false; }
    finally { setSaving(null); }
  }

  const today = new Date().toISOString().slice(0, 10);
  const groupedLeave = useMemo(() => ({ upcoming: leave.filter((entry) => entry.active && (entry.ends_on ?? "") >= today), past: leave.filter((entry) => entry.active && (entry.ends_on ?? "") < today), cancelled: leave.filter((entry) => !entry.active) }), [leave, today]);
  const currentAssignments = assignments.filter((entry) => entry.active && (!entry.effective_to || entry.effective_to >= today));
  const historicalAssignments = assignments.filter((entry) => !currentAssignments.includes(entry));

  return <div className="space-y-7">
    <Section title="Working hours"><ScheduleForm submit={(data) => send(`/api/admin/doctors/${doctorId}/schedule`, "POST", data, "Working hours added.")} saving={Boolean(saving)} disabled={!permissions.schedule} submitLabel="Add working hours" /><EntryList entries={schedules} empty="No working hours yet." render={(entry) => <><span>{weekday(entry.weekday)} {entry.start_time}–{entry.end_time}{entry.break_start_time ? ` · Break ${entry.break_start_time}–${entry.break_end_time ?? ""}` : ""}</span>{permissions.schedule && <Actions onEdit={() => setEditing({ kind: "schedule", entry })} onEnd={() => send(`/api/admin/doctors/${doctorId}/schedule/${entry.id}`, "DELETE", undefined, "Working hours ended.")} disabled={Boolean(saving)} />}</>} /></Section>
    <Section title="Leave"><LeaveForm submit={(data) => send(`/api/admin/doctors/${doctorId}/leave`, "POST", data, "Leave added.")} saving={Boolean(saving)} disabled={!permissions.leave} submitLabel="Add leave" /><LeaveGroup title="Upcoming" entries={groupedLeave.upcoming} editable={permissions.leave} onEdit={(entry) => setEditing({ kind: "leave", entry })} onCancel={(entry) => send(`/api/admin/doctors/${doctorId}/leave/${entry.id}`, "DELETE", undefined, "Leave cancelled.")} saving={Boolean(saving)} /><LeaveGroup title="Past" entries={groupedLeave.past} editable={permissions.leave} onEdit={(entry) => setEditing({ kind: "leave", entry })} onCancel={(entry) => send(`/api/admin/doctors/${doctorId}/leave/${entry.id}`, "DELETE", undefined, "Leave cancelled.")} saving={Boolean(saving)} /><LeaveGroup title="Cancelled" entries={groupedLeave.cancelled} editable={false} onEdit={() => undefined} onCancel={() => undefined} saving={false} /></Section>
    <Section title="Blocked time"><BlockForm submit={(data) => send(`/api/admin/doctors/${doctorId}/blocked-time`, "POST", data, "Blocked time added.")} saving={Boolean(saving)} disabled={!permissions.block} submitLabel="Block time" /><EntryList entries={blocked} empty="No blocked time." render={(entry) => <><span>{formatDateTime(entry.starts_at)}–{formatDateTime(entry.ends_at)}{entry.source ? ` · ${entry.source}` : ""}{!entry.active ? " (cancelled)" : ""}</span>{entry.active && permissions.block && <Actions onEdit={() => setEditing({ kind: "block", entry })} onEnd={() => send(`/api/admin/doctors/${doctorId}/blocked-time/${entry.id}`, "DELETE", undefined, "Blocked time cancelled.")} disabled={Boolean(saving)} />}</>} /></Section>
    <Section title="Room assignments"><AssignmentForm rooms={rooms} submit={(data) => send(`/api/admin/doctors/${doctorId}/room-assignments`, "POST", data, "Room assigned.")} saving={Boolean(saving)} disabled={!permissions.assignment} submitLabel="Assign room" /><AssignmentGroup title="Current assignment" entries={currentAssignments} rooms={rooms} editable={permissions.assignment} onEdit={(entry) => setEditing({ kind: "assignment", entry })} onEnd={(entry) => send(`/api/admin/doctors/${doctorId}/room-assignments/${entry.id}`, "DELETE", { effectiveTo: today }, "Room assignment ended.")} saving={Boolean(saving)} /><AssignmentGroup title="Assignment history" entries={historicalAssignments} rooms={rooms} editable={permissions.assignment} onEdit={(entry) => setEditing({ kind: "assignment", entry })} onEnd={(entry) => send(`/api/admin/doctors/${doctorId}/room-assignments/${entry.id}`, "DELETE", { effectiveTo: today }, "Room assignment ended.")} saving={Boolean(saving)} /></Section>
    {editing && <EditDialog editing={editing} rooms={rooms} close={() => setEditing(null)} save={async (data) => { const route = editing.kind === "schedule" ? "schedule" : editing.kind === "leave" ? "leave" : editing.kind === "block" ? "blocked-time" : "room-assignments"; const result = await send(`/api/admin/doctors/${doctorId}/${route}/${editing.entry.id}`, "PATCH", data, "Changes saved."); if (result) setEditing(null); }} saving={Boolean(saving)} />}
    {success && <p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{success}</p>}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="text-xl font-bold">{title}</h2>{children}</section>; }
type Submit = (body: Record<string, unknown>) => unknown | Promise<unknown>;
function ScheduleForm({ submit, saving, disabled, submitLabel, entry }: { submit: Submit; saving: boolean; disabled: boolean; submitLabel: string; entry?: Entry }) { return <form action={(data) => { void submit(Object.fromEntries(data)); }} className="grid gap-2 rounded-xl border bg-white p-4 sm:grid-cols-3"><select name="weekday" defaultValue={entry?.weekday ?? 0} className="min-h-11 rounded border px-3" disabled={disabled}>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input name="startTime" type="time" required defaultValue={entry?.start_time ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="endTime" type="time" required defaultValue={entry?.end_time ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="breakStartTime" type="time" defaultValue={entry?.break_start_time ?? ""} aria-label="Break start" className="min-h-11 rounded border px-3" disabled={disabled}/><input name="breakEndTime" type="time" defaultValue={entry?.break_end_time ?? ""} aria-label="Break end" className="min-h-11 rounded border px-3" disabled={disabled}/><input name="timezone" defaultValue={entry?.timezone ?? "Asia/Kolkata"} className="min-h-11 rounded border px-3" disabled={disabled}/><button disabled={saving || disabled} className="min-h-11 rounded bg-blue-600 px-4 font-semibold text-white disabled:opacity-50 sm:col-span-3">{saving ? "Saving…" : submitLabel}</button></form>; }
function LeaveForm({ submit, saving, disabled, submitLabel, entry }: { submit: Submit; saving: boolean; disabled: boolean; submitLabel: string; entry?: Entry }) { return <form action={(data) => { void submit(Object.fromEntries(data)); }} className="grid gap-2 rounded-xl border bg-white p-4 sm:grid-cols-3"><input name="startsOn" type="date" required defaultValue={entry?.starts_on ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="endsOn" type="date" required defaultValue={entry?.ends_on ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="reason" placeholder="Reason" defaultValue={entry?.reason ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><button disabled={saving || disabled} className="min-h-11 rounded bg-blue-600 px-4 font-semibold text-white disabled:opacity-50 sm:col-span-3">{saving ? "Saving…" : submitLabel}</button></form>; }
function BlockForm({ submit, saving, disabled, submitLabel, entry }: { submit: Submit; saving: boolean; disabled: boolean; submitLabel: string; entry?: Entry }) { return <form action={(data) => { void submit(Object.fromEntries(data)); }} className="grid gap-2 rounded-xl border bg-white p-4 sm:grid-cols-3"><input name="startsAt" type="datetime-local" required defaultValue={toLocal(entry?.starts_at)} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="endsAt" type="datetime-local" required defaultValue={toLocal(entry?.ends_at)} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="source" placeholder="Reason / source" defaultValue={entry?.source ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><button disabled={saving || disabled} className="min-h-11 rounded bg-blue-600 px-4 font-semibold text-white disabled:opacity-50 sm:col-span-3">{saving ? "Saving…" : submitLabel}</button></form>; }
function AssignmentForm({ rooms, submit, saving, disabled, submitLabel, entry }: { rooms: Room[]; submit: Submit; saving: boolean; disabled: boolean; submitLabel: string; entry?: Entry }) { return <form action={(data) => { void submit(Object.fromEntries(data)); }} className="grid gap-2 rounded-xl border bg-white p-4 sm:grid-cols-3"><select name="roomId" required defaultValue={entry?.room_id ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}><option value="">Select room</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select><input name="effectiveFrom" type="date" defaultValue={entry?.effective_from ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><input name="effectiveTo" type="date" defaultValue={entry?.effective_to ?? ""} className="min-h-11 rounded border px-3" disabled={disabled}/><button disabled={saving || disabled} className="min-h-11 rounded bg-blue-600 px-4 font-semibold text-white disabled:opacity-50 sm:col-span-3">{saving ? "Saving…" : submitLabel}</button></form>; }
function Actions({ onEdit, onEnd, disabled, endLabel = "End" }: { onEdit: () => void; onEnd: () => void; disabled: boolean; endLabel?: string }) { return <span className="flex gap-2"><button type="button" onClick={onEdit} disabled={disabled} className="min-h-11 rounded border px-3 text-sm disabled:opacity-50">Edit</button><button type="button" onClick={onEnd} disabled={disabled} className="min-h-11 rounded border px-3 text-sm text-red-700 disabled:opacity-50">{endLabel}</button></span>; }
function EntryList({ entries, empty, render }: { entries: Entry[]; empty: string; render: (entry: Entry) => React.ReactNode }) { return entries.length ? <div className="grid gap-2">{entries.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border bg-white p-3 text-sm">{render(entry)}</div>)}</div> : <p className="rounded-lg border border-dashed p-4 text-sm text-slate-500">{empty}</p>; }
function LeaveGroup({ title, entries, editable, onEdit, onCancel, saving }: { title: string; entries: Entry[]; editable: boolean; onEdit: (entry: Entry) => void; onCancel: (entry: Entry) => void; saving: boolean }) { return <div className="space-y-2"><h3 className="font-semibold">{title}</h3><EntryList entries={entries} empty={`No ${title.toLowerCase()} leave.`} render={(entry) => <><span>{entry.starts_on}–{entry.ends_on}{entry.reason ? ` · ${entry.reason}` : ""}</span>{editable && <Actions onEdit={() => onEdit(entry)} onEnd={() => onCancel(entry)} endLabel="Cancel" disabled={saving} />}</>} /></div>; }
function AssignmentGroup({ title, entries, rooms, editable, onEdit, onEnd, saving }: { title: string; entries: Entry[]; rooms: Room[]; editable: boolean; onEdit: (entry: Entry) => void; onEnd: (entry: Entry) => void; saving: boolean }) { return <div className="space-y-2"><h3 className="font-semibold">{title}</h3><EntryList entries={entries} empty={`No ${title.toLowerCase()}.`} render={(entry) => <><span>{rooms.find((room) => room.id === entry.room_id)?.name ?? "Room"} · {entry.effective_from ?? "Current"}–{entry.effective_to ?? "Open"}{!entry.active ? " (ended)" : ""}</span>{editable && entry.active && <Actions onEdit={() => onEdit(entry)} onEnd={() => onEnd(entry)} disabled={saving} />}</>} /></div>; }
function EditDialog({ editing, rooms, close, save, saving }: { editing: { kind: EditKind; entry: Entry }; rooms: Room[]; close: () => void; save: Submit; saving: boolean }) { const common = { entry: editing.entry, submit: save, saving, disabled: false, submitLabel: "Save changes" }; const form = editing.kind === "schedule" ? <ScheduleForm {...common} /> : editing.kind === "leave" ? <LeaveForm {...common} /> : editing.kind === "block" ? <BlockForm {...common} /> : <AssignmentForm {...common} rooms={rooms} />; return <div role="dialog" aria-modal="true" aria-label={`Edit ${editing.kind}`} className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/40 p-4"><div className="mx-auto mt-8 max-w-2xl rounded-2xl bg-white p-5 shadow-xl"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold">Edit {editing.kind === "block" ? "blocked time" : editing.kind}</h2><button type="button" onClick={close} className="min-h-11 rounded px-3">Close</button></div>{form}</div></div>; }
function weekday(value?: number) { return ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][value ?? 0]; }
function formatDateTime(value?: string) { return value ? new Date(value).toLocaleString() : ""; }
function toLocal(value?: string) { return value ? value.slice(0, 16) : ""; }
