"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Onboarding = { owner_email: string; owner_full_name: string; role: "owner" | "manager"; status: string; invitation_sent_at: string | null; activation_completed_at: string | null; failure_code: string | null; };

export default function OwnerOnboardingCard({ clinicId, onboarding, canUpdate, available }: { clinicId: string; onboarding: Onboarding | null; canUpdate: boolean; available: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState("");
  async function action(path: "resend" | "retry-profile") { await post(path); }
  async function setup() { await post("setup", { fullName, email, role: "owner" }); }
  async function post(path: string, body?: Record<string, string>) { if (busy) return; setBusy(true); setMessage(null); try { const response = await fetch(`/api/admin/clinics/${clinicId}/owner-onboarding/${path}`, { method: "POST", ...(body ? { headers: { "content-type": "application/json" }, body: JSON.stringify(body) } : {}) }); const result = await response.json().catch(() => ({})); if (!response.ok) setMessage(typeof result.message === "string" ? result.message : "Unable to update owner onboarding."); else router.refresh(); } catch { setMessage("Unable to update owner onboarding. Check your connection and try again."); } finally { setBusy(false); } }
  if (!available) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-900">Owner onboarding unavailable</h2><p className="mt-1 text-sm text-amber-800">Apply approved migration 0015 before creating or recovering clinic owner invitations.</p></section>;
  if (!onboarding) return <section className="rounded-2xl border p-5"><h2 className="font-semibold">Owner invitation</h2><p className="mt-1 text-sm text-muted-foreground">No owner invitation has been recorded for this clinic.</p>{canUpdate && <form onSubmit={(event) => { event.preventDefault(); void setup(); }} className="mt-4 grid gap-3 sm:grid-cols-3"><input required value={fullName} onChange={(event) => setFullName(event.target.value)} placeholder="Owner full name" className="min-h-11 rounded-lg border px-3" /><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Owner email" className="min-h-11 rounded-lg border px-3" /><button disabled={busy} className="min-h-11 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white disabled:opacity-60">Set Up Owner Account</button></form>}{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</section>;
  const failed = onboarding.status === "failed";
  return <section className="rounded-2xl border bg-background p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Owner invitation</h2><p className="mt-1 text-sm text-muted-foreground">{onboarding.owner_full_name} · {onboarding.owner_email}</p></div><span className={`rounded-full px-3 py-1 text-sm font-medium ${onboarding.status === "active" ? "bg-emerald-50 text-emerald-700" : failed ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-800"}`}>{label(onboarding.status)}</span></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><Info label="Role" value={onboarding.role} /><Info label="Invitation sent" value={onboarding.invitation_sent_at ? new Date(onboarding.invitation_sent_at).toLocaleString() : "Pending"} /><Info label="Activated" value={onboarding.activation_completed_at ? new Date(onboarding.activation_completed_at).toLocaleString() : "Not activated"} /></dl>{failed && <p className="mt-3 text-sm text-red-700">Invitation needs recovery. No provider details are stored.</p>}{canUpdate && onboarding.status !== "active" && <div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={() => void action("resend")} className="min-h-11 rounded-lg border px-4 text-sm font-medium disabled:opacity-60">Resend invitation</button>{failed && <button disabled={busy} onClick={() => void action("retry-profile")} className="min-h-11 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white disabled:opacity-60">Retry profile setup</button>}</div>}{message && <p role="alert" className="mt-3 text-sm text-red-700">{message}</p>}</section>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="font-medium">{label}</dt><dd className="mt-1 text-muted-foreground">{value}</dd></div>; }
function label(status: string): string { return status === "invited" ? "Invitation Sent" : status === "pending" || status === "inviting" ? "Pending" : status.slice(0, 1).toUpperCase() + status.slice(1); }
